### ISSUE TITLE
Skipping certain images due to an error

### ISSUE THREAD

**Issue by GhanimAlSuwaidi** [Hvitgar/stylize-datasets#12]
The code skips over some images with an error but not sure what the error is. it just says due to an error.

**Comment by annopackage** [comment]
Hi, do you know the specific reason of it?

**Comment by MMathisLab** [comment]
Hi, could you provide the full traceback?

**Comment by bmitzkus** [comment]
@annopackage most likely it is related to PIL not being able to load the image. Usually corrupted files/decompression bomb warnings. The error handling can be found in this [line](https://github.com/bethgelab/stylize-datasets/blob/e870e8c53152a42fd4b91d43dcfe3906818009a9/stylize.py#L148), the image in question will just be skipped and it's path is written to a file (so that you can check later for problems with the image)

just noticed that while the try...catch block would catch both errors on style and content loading, only the content path will be added to the skipped_imgs.txt (even if the style image caused the error)
