### ISSUE TITLE
Converting from Torch to Pytorch

### ISSUE THREAD

**Issue by omar-araboghli** [Hvitgar/stylize-datasets#2]
Please refer to this issue: 
https://github.com/naoto0804/pytorch-AdaIN/issues/20

**Comment by bmitzkus** [comment]
This happens when you try to convert the models with a recent pyTorch version. For conversion (and only for conversion), pyTorch 0.4 is needed since `torch-to-pytorch.py` uses legacy code that has been removed past version 0.4.

You could set up a virtual environment in which you `pip install torch==0.4` and run the conversion script (this only needs to be done once, the converted models can then be stored and used whenever you want).
